[[main]]
  name = "About"
  url = "/about"
  weight = 10

[[main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 20

[[main]]
  name = "Posts"
  url = "/posts"
  weight = 30

[[main]]
  name = "CTFs"
  url = "/ctfs"
  weight = 40